=== MaxMahem/php-X937/library/Records/X937Structure.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.0"
           elementFormDefault="qualified">

    <xs:simpleType name="recordName">
        <xs:annotation>
            <xs:documentation>Besides being a valid element name (handled by 
                base type xs:Name, all records must end in 'Record'.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:Name">
            <xs:pattern value="(.)+Record"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="usage">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="validation">
        <xs:annotation>
            <xs:documentation>Not currently used.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="R"/>
            <xs:enumeration value="P"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="maxOccurs">
        <xs:annotation>
            <xs:documentation>This should basically be a copy of the xsd type.</xs:documentation>
        </xs:annotation>
        <xs:union>
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="0"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:simpleType>
                <xs:restriction base="xs:NMTOKEN">
                    <xs:enumeration value="unbounded" />
                </xs:restriction>
            </xs:simpleType>
        </xs:union>
    </xs:simpleType>
    
    <xs:complexType name="control">
        <xs:sequence>
            <xs:element name="record" type="record" maxOccurs="unbounded" />
            <xs:element name="control" type="control" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="record" type="record" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:Name" use="required" />
        <xs:attribute name="usage" type="usage" use="required" />
        <xs:attribute name="maxOccurs" type="maxOccurs" use="optional" />
        <xs:attribute name="id" use="optional" />
        <xs:attribute name="scope" use="optional" />
    </xs:complexType>
    
    <xs:complexType name="record">
        <xs:attribute name="name" type="recordName" use="required" />
        <xs:attribute name="usage" type="usage" use="required" />
        <xs:attribute name="maxOccurs" type="maxOccurs" use="optional" />
    </xs:complexType>

    <xs:element name="file">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="control" type="control" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="filenameRoot" use="required" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== MaxMahem/php-X937/ANSI-X9-100-187-Structure.xml
<?xml version="1.0" encoding="UTF-8"?>
<file 
    xsi:noNamespaceSchemaLocation='X937Structure.xsd'
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    filenameRoot='ANSI-X9-100-187'>
    <control name="File" usage="M">
        <record name="FileHeaderRecord" usage="M" />
        <!-- Credit Item Records and User Records can occur anywhere between here
             and the file control record. The presence of these records is currently
             not allowed -->
        <control name="CashLetter" usage="M" maxOccurs="unbounded">
            <record name="CashLetterHeaderRecord" usage="M" />
            <control name="Bundle" usage="M" maxOccurs="unbounded">
                <record name="BundleHeaderRecord" usage="M" />
                <control name="Item" usage="M" maxOccurs="unbounded">
                    <record name="CheckDetailRecord" usage="M" />
                    <record name="CheckDetailAddendumARecord" usage="C" maxOccurs="unbounded" />
                    <!-- CheckDetailAddenedumBRecords have an additional constraint that they must be preceded by
                         a CheckDetailAddenedumARecord if they occur. That constraint is not enforced here -->
                    <record name="CheckDetailAddendumBRecord" usage="C" maxOccurs="1" />
                    <record name="CheckDetailAddendumCRecord" usage="C" maxOccurs="unbounded" />
                    <control name="View" usage="C" maxOccurs="unbounded">
                        <record name="ImageViewDetailRecord" usage="M" />
                        <record name="ImageViewDataRecord" usage="M" />
                        <record name="ImageViewAnalysisRecord" usage="C"/>
                    </control>
                </control>
                <record name="BundleControlRecord" usage="M" />
            </control>
            <record name="CashLetterControlRecord" usage="M" />
        </control>
        <record name="RoutingNumberSummaryRecord" usage="C" maxOccurs="unbounded"/>
        <record name="FileControlRecord" usage="M" />
    </control>
</file>
