=== MaxMahem/php-X937/Records/X937Records.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           version="1.0"
           elementFormDefault="qualified">

    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9 \-]+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="recordName">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z0-9 \-]+ Record"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="recordType">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{2,8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="usage">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"/>
            <xs:enumeration value="C"/>
            <xs:enumeration value="O"/>
            <xs:enumeration value="F"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="validation">
        <xs:restriction base="xs:string">
            <xs:enumeration value="R"/>
            <xs:enumeration value="P"/>
            <xs:enumeration value="N"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="variableLength">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="ref" type="xs:IDREFS" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="dictonary">
        <xs:sequence>
            <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="key" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="comprehensive" type="xs:boolean" use="required"/>
        <xs:attribute name="ref" type="xs:IDREF" use="optional"/>
        <xs:attribute name="id" type="xs:ID" use="optional"/>
    </xs:complexType>

    <xs:complexType name="abstractField" mixed="true">
        <xs:sequence/>
        <xs:attribute name="order" type="xs:int" use="required"/>
        <xs:attribute name="id" type="xs:ID" use="optional"/>
    </xs:complexType>
    <xs:complexType name="concreteField" mixed="true">
        <xs:complexContent>
            <xs:extension base="abstractField">
                <xs:sequence>
                    <xs:element name="name" type="name"/>
                    <xs:element name="usage" type="usage"/>
                    <xs:element name="type">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="A"/>
                                <xs:enumeration value="N"/>
                                <xs:enumeration value="NB"/>
                                <xs:enumeration value="NS"/>
                                <xs:enumeration value="NBSM"/>
                                <xs:enumeration value="NBSMOS"/>
                                <xs:enumeration value="AN"/>
                                <xs:enumeration value="ANS"/>
                                <xs:enumeration value="ANU">
                                    <xs:annotation>
                                        <xs:documentation>
                                            Alphanumeric, Uppercase Only
                                        </xs:documentation>
                                    </xs:annotation>
                                </xs:enumeration>
                                <xs:enumeration value="Binary"/>
                                <xs:enumeration value="B"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="subtype" minOccurs="0">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Routing"/>
                                <xs:enumeration value="Date"/>
                                <xs:enumeration value="Time"/>
                                <xs:enumeration value="Phone"/>
                                <xs:enumeration value="Blank"/>
                                <xs:enumeration value="Amount"/>
                                <xs:enumeration value="Count"/>
                                <xs:enumeration value="Bytes"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="dictonary" type="dictonary" minOccurs="0"/>
                    <xs:element name="validation" type="validation"/>
                    <xs:element ref="positionGroup"/>
                    <xs:element ref="lengthGroup"/>
                    <xs:element name="valueKey" type="xs:string" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="predefinedField" mixed="true">
        <xs:complexContent>
            <xs:extension base="abstractField">
                <xs:attribute name="ref" type="xs:IDREF" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="abstractRecord" mixed="true">
        <xs:sequence>
            <xs:element name="name" type="recordName"/>
            <xs:element name="type" type="recordType"/>
            <xs:element name="usage" type="usage"/>
            <xs:element name="validation" type="validation"/>
        </xs:sequence>
        <xs:attribute name="type" type="recordType" use="optional"/>
    </xs:complexType>
    <xs:complexType name="forbiddenRecord" mixed="true">
        <xs:complexContent>
            <xs:extension base="abstractRecord"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="record" mixed="true">
        <xs:complexContent>
            <xs:extension base="abstractRecord">
                <xs:sequence>
                    <xs:element ref="lengthGroup"/>
                    <xs:element name="fieldCount" type="xs:int"/>
                    <xs:element name="fields">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element ref="fieldGroup" maxOccurs="unbounded"/>
                            </xs:sequence>
                        </xs:complexType>

                        <xs:unique name="unqiueFieldOrder">
                            <xs:selector xpath="field|predefined"/>
                            <xs:field xpath="@order"/>
                        </xs:unique>
                        <xs:unique name="unqiueFieldValueKey">
                            <xs:selector xpath="field"/>
                            <xs:field xpath="valueKey"/>
                        </xs:unique>

                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:element name="records">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="dictonaries">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dictonary" type="dictonary" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="predefines">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="field" type="concreteField"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element ref="recordGroup" maxOccurs="unbounded"/>

            </xs:sequence>
            <xs:attribute name="filenameRoot" use="required" />
        </xs:complexType>

        <xs:unique name="uniqueRecordTypeAttribute">
            <xs:selector xpath="record|forbidden"/>
            <xs:field xpath="@type"/>
        </xs:unique>
        <xs:unique name="uniqueRecordNames">
            <xs:selector xpath="record|forbidden|undefined"/>
            <xs:field xpath="name"/>
        </xs:unique>
        <xs:unique name="uniqueRecordType">
            <xs:selector xpath="record|forbidden|undefined"/>
            <xs:field xpath="type"/>
        </xs:unique>

    </xs:element>

    <xs:element name="positionGroup" abstract="true"/>
    <xs:element name="position" type="xs:int" substitutionGroup="positionGroup"/>
    <xs:element name="variablePosition" type="xs:string" substitutionGroup="positionGroup"/>

    <xs:element name="lengthGroup" abstract="true"/>
    <xs:element name="length" type="xs:int" substitutionGroup="lengthGroup"/>
    <xs:element name="variableLength" type="variableLength" substitutionGroup="lengthGroup"/>

    <xs:element name="fieldGroup" abstract="true"/>
    <xs:element name="field" type="concreteField" substitutionGroup="fieldGroup"/>
    <xs:element name="predefined" type="predefinedField" substitutionGroup="fieldGroup"/>

    <xs:element name="recordGroup" abstract="true"/>
    <xs:element name="record" type="record" substitutionGroup="recordGroup"/>
    <xs:element name="forbidden" type="forbiddenRecord" substitutionGroup="recordGroup"/>
    <xs:element name="undefined" type="forbiddenRecord" substitutionGroup="recordGroup"/>

</xs:schema>

=== MaxMahem/php-X937/ANSI-X9-100-187-Records.xml
<?xml version="1.0" encoding="UTF-8"?>
<records
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation='Records\X937Records.xsd'
        filenameRoot='ANSI-X9-100-187'>

    <dictonaries>
        <dictonary id="dictRecordType" comprehensive="true">
            <value key="01">File Header Record</value>
            <value key="10">Cash Letter Header Record</value>
            <value key="20">Bundle Header Record</value>
            <value key="25">Check Detail Record</value>
            <value key="26">Check Detail Addenedum A Record</value>
            <value key="27">Check Detail Addenedum B Record</value>
            <value key="28">Check Detail Addenedum C Record</value>
            <value key="50">Image View Detail Record</value>
            <value key="52">Image View Data Record</value>
            <value key="54">Image View Analysis Record</value>
            <value key="70">Bundle Control Record</value>
            <value key="90">Cash Letter Control Record</value>
            <value key="99">File Control Record</value>
        </dictonary>
        <dictonary id="dictCollectionType" comprehensive="true">
            <value key='00'>Preliminary Forward Information</value>
            <value key='01'>Forward Presentment</value>
            <value key='02'>Forward Presentment - Same Day Settlement</value>
            <value key='03'>Returns</value>
            <value key='04'>Return Notification</value>
            <value key='05'>Preliminary Return Notification</value>
            <value key='06'>Final Return Notification</value>
            <value key='20'>No Detail</value>
            <value key='99'>Bundles not the same collection type</value>
        </dictonary>
        <dictonary id="dictDocumentationType" comprehensive="true">
            <value key="A">No image provided, paper provided separately</value>
            <value key="B">No image provided, paper provided separately, image upon request</value>
            <value key="C">Image provided separately, no paper provided</value>
            <value key="D">Image provided separately, no paper provided, image upon request</value>
            <value key="E">Image and paper provided separately</value>
            <value key="F">Image and paper provided separately, image upon request</value>
            <value key="G">Image included, no paper provided</value>
            <value key="H">Image included, no paper provided, image upon request</value>
            <value key="I">Image included, paper provided separately</value>
            <value key="J">Image included, paper provided separately, image upon request</value>
            <value key="K">No image provided, no paper provided</value>
            <value key="L">No image provided, no paper provided, image upon request</value>
            <value key="M">No image provided, Electronic Check provided separately</value>
            <value key="Z">Not Same Typeâ€“Documentation associated with each item in Cash Letter will be different.
            </value>
        </dictonary>
        <dictonary id="dictItemDocumentationType" comprehensive="true">
            <value key="A">No image provided, paper provided separately</value>
            <value key="B">No image provided, paper provided separately, image upon request</value>
            <value key="C">Image provided separately, no paper provided</value>
            <value key="D">Image provided separately, no paper provided, image upon request</value>
            <value key="E">Image and paper provided separately</value>
            <value key="F">Image and paper provided separately, image upon request</value>
            <value key="G">Image included, no paper provided</value>
            <value key="H">Image included, no paper provided, image upon request</value>
            <value key="I">Image included, paper provided separately</value>
            <value key="J">Image included, paper provided separately, image upon request</value>
            <value key="K">No image provided, no paper provided</value>
            <value key="L">No image provided, no paper provided, image upon request</value>
            <value key="M">No image provided, Electronic Check provided separately</value>
        </dictonary>
        <dictonary id="dictTruncationIndicator" comprehensive="true">
            <value key="Y">Truncated</value>
            <value key="N">Not Truncated</value>
        </dictonary>
        <dictonary id="dictConversionIndicator" comprehensive="true">
            <value key="0">Did not convert physical document</value>
            <value key="1">Original paper converted to IRD</value>
            <value key="2">Original paper converted to image</value>
            <value key="3">IRD converted to another IRD</value>
            <value key="4">IRD converted to image of IRD</value>
            <value key="5">Image converted to an IRD</value>
            <value key="6">Image converted to another image (e.g., transcoded)</value>
            <value key="7">Did not convert image (e.g., same as source)</value>
            <value key="8">Undetermined</value>
        </dictonary>
        <dictonary id="dictCorrectionIndicator" comprehensive="true">
            <value key="0">No Repair</value>
            <value key="1">Repaired (form of repair unknown)</value>
            <value key="2">Repaired without Operator intervention</value>
            <value key="3">Repaired with Operator intervention</value>
            <value key="4">Undetermined if repair has been done or not</value>
        </dictonary>
        <dictonary id="dictArchiveTypeIndicator" comprehensive="true">
            <value key="A">Microfilm</value>
            <value key="B">Image</value>
            <value key="C">Paper</value>
            <value key="D">Microfilm and image</value>
            <value key="E">Microfilm and paper</value>
            <value key="F">Image and paper</value>
            <value key="G">Microfilm, image and paper</value>
            <value key="H">Electronic Check Instrument</value>
            <value key="I">None</value>
        </dictonary>
        <dictonary id="dictReturnCodes" comprehensive="true">
            <value key="A">NSF - Not Sufficent Funds'</value>
            <value key="B">UCF - Uncollected Funds Hold</value>
            <value key="C">Stop Payment</value>
            <value key="D">Closed Account</value>
            <value key="E">UTLA - Unable to Locate Account</value>
            <value key="F">Frozen/Blocked Account</value>
            <value key="G">Stale Dated</value>
            <value key="H">Post Dated</value>
            <value key="I">Endorsement Missing</value>
            <value key="J">Endorsement Irregular</value>
            <value key="K">Signature Missing</value>
            <value key="L">Signature Irregular</value>
            <value key="M">Non-Cash Item (Non-Negotiable)</value>
            <value key="N">Altered/Fictious Item</value>
            <value key="O">Unable to Process (Mutilated Item)</value>
            <value key="P">Item Exceeds Dollar Limit</value>
            <value key="Q">Not Authorized</value>
            <value key="R">Branch/Account Sold (Wrong Bank)</value>
            <value key="S">Refer to Maker</value>
            <value key="T">Stop Payment Suspect</value>
            <value key="U">Unusable Image</value>
            <value key="V">Image Fails Security Check</value>
            <value key="W">Cannot Determine Amount</value>
        </dictonary>
        <dictonary id="dictImagingTest" comprehensive="true">
            <value key="0">Test not done</value>
            <value key="1">Condition Present</value>
            <value key="2">Condition not present</value>
        </dictonary>
        <dictonary id="dictImageUseability" comprehensive="true">
            <value key="0">Test not done</value>
            <value key="1">Area unusable</value>
            <value key="2">Area usable</value>
        </dictonary>
        <dictonary id="dictCreditTotalIndicator" comprehensive="true">
            <value key="0">Credit Items are not included in totals</value>
            <value key="1">Credit Items are included in totals</value>
        </dictonary>
    </dictonaries>

    <predefines>
        <field order="1" id="fieldRecordType">Record Type
            <name>Record Type</name>
            <usage>M</usage>
            <type>N</type>
            <dictonary comprehensive="true" ref="dictRecordType"/>
            <validation>R</validation>
            <position>1</position>
            <length>2</length>
        </field>
    </predefines>

    <record type="01">File Header Record
        <name>File Header Record</name>
        <type>01</type>
        <usage>M</usage>
        <validation>R</validation>
        <length>80</length>
        <fieldCount>14</fieldCount>
        <fields>
            <predefined order="1" ref="fieldRecordType">Record Type</predefined>
            <field order="2">Standard Level
                <name>Standard Level</name>
                <usage>M</usage>
                <type>N</type>
                <dictonary comprehensive="true">
                    <value key="35">X9.100-187-2013/2016</value>
                    <value key="30">X9.100-187-2008</value>
                    <value key="03">X9.100-197</value>
                </dictonary>
                <validation>R</validation>
                <position>3</position>
                <length>2</length>
            </field>
            <field order="3">Test File Indicator
                <name>Test File Indicator</name>
                <usage>M</usage>
                <type>A</type>
                <dictonary comprehensive="true">
                    <value key="P">Production</value>
                    <value key="T">Test</value>
                </dictonary>
                <validation>R</validation>
                <position>5</position>
                <length>1</length>
