=== MaxMahem/php-X937/Record/X937Specification.xsd
<?xml version="1.0"?>
<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

<xs:simpleType name="name">
    <xs:restriction base="xs:string">
        <xs:pattern value="[a-zA-Z ]+" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="recordType">
    <xs:restriction base="xs:int">
        <xs:pattern value="[0-9][0-9]" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="usage">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Mandatory" />
        <xs:enumeration value="Conditional" />
        <xs:enumeration value="Optional" />
        <xs:enumeration value="Forbidden" />
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="validation">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Required" />
        <xs:enumeration value="Required if Present" />
        <xs:enumeration value="None" />
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="dictonary">
    <xs:sequence>
        <xs:element name="value" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
                <xs:simpleContent>
                    <xs:extension base="xs:string">
                        <xs:attribute name="key" type="xs:string" />
                    </xs:extension>
                </xs:simpleContent>
            </xs:complexType>
        </xs:element>
    </xs:sequence>
    <xs:attribute name="comprehensive" type="xs:boolean" use="required" />
    <xs:attribute name="ref"           type="xs:IDREF"   use="optional" />
    <xs:attribute name="id"            type="xs:ID"      use="optional" />
</xs:complexType>
    
<xs:element name="records">
    <xs:complexType><xs:sequence>
       
    <xs:element name="dictonaries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="dictonary" type="dictonary" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="record" maxOccurs="unbounded"><xs:complexType mixed="true">
        <xs:sequence>
            <xs:element name="name" type="name"/>
            <xs:element name="type" type="recordType" />
            <xs:element name="usage" type="usage" />
            <xs:element name="validation" type="validation" />
            <xs:element name="length">
                <xs:simpleType>
                    <xs:union>
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="Variable" />
                            </xs:restriction>
                        </xs:simpleType>
                        <xs:simpleType>
                            <xs:restriction base="xs:int" />
                        </xs:simpleType>
                    </xs:union>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fields"><xs:complexType>
                <xs:sequence>
                    <xs:element name="field" maxOccurs="unbounded"><xs:complexType mixed="true">
                        <xs:all minOccurs="1">
                            <xs:element name="name"  type="name" />
                            <xs:element name="usage" type="usage" />
                            <xs:element name="type">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Alphameric" />
                                        <xs:enumeration value="Numeric" />
                                        <xs:enumeration value="Alphanumeric" />
                                        <xs:enumeration value="Alphanumeric Special" />
                                        <xs:enumeration value="Alphanumeric Upper Only" />
                                        <xs:enumeration value="Alphanumeric Space" />
                                        <xs:enumeration value="Blank" />
                                        <xs:enumeration value="Date" />
                                        <xs:enumeration value="Time" />
                                        <xs:enumeration value="Routing Number" />
                                        <xs:enumeration value="Phone Number" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="dictonary" type="dictonary" minOccurs="0" />
                            <xs:element name="validation" type="validation" />
                            <xs:element name="position" type="xs:int" />
                            <xs:element name="length"   type="xs:int" />
                        </xs:all>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType></xs:element>
                </xs:sequence>
                <xs:attribute name="count" use="required" type="xs:integer" />
            </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type" type="recordType" use="required" />
    </xs:complexType></xs:element>
    
    </xs:sequence></xs:complexType>
    
    <xs:unique name="uniqueRecords">
        <xs:selector xpath="record" />
        <xs:field xpath="@type" />
    </xs:unique>
</xs:element>
</xs:schema>

=== MaxMahem/php-X937/Record/Specification4.xml
<?xml version="1.0" encoding="UTF-8"?>
<records
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='X937Specification.xsd'>
    
    <dictonaries>
        <dictonary comprehensive="true" id="recordType">
            <value key="01">File Header Record</value>
            <value key="10">Cash Letter Header Record</value>
        </dictonary>
    </dictonaries>
    
    <record type="01">File Header Record
        <name>File Header Record</name>
        <type>01</type>
        <usage>M</usage>
        <validation>R</validation>
        <length>80</length>
        <fields count="14">
            <field id="1">Record Type
                <name>Record Type</name>
                <usage>M</usage>
                <type>N</type>
                <dictonary comprehensive="true" ref="recordType"/>
                <validation>R</validation>
                <position>1</position>
                <length>2</length>
            </field>
            <field id="2">Standard Level
                <name>Standard Level</name>
                <usage>M</usage>
                <type>N</type>
                <dictonary comprehensive="true">
                    <value key="03">X9.100-197</value>
                </dictonary>
                <validation>R</validation>
                <position>3</position>
                <length>2</length>
            </field>
            <field id="3">Test File Indicator
                <name>Test File Indicator</name>
                <usage>M</usage>
                <type>A</type>
                <dictonary comprehensive="false"/>
                <validation>R</validation>
                <position>5</position>
                <length>1</length>
            </field>
            <field id="4">Immediate Destination Routing Number
                <name>Immediate Destination Routing Number</name>
                <usage>M</usage>
                <type>N</type>
                <subtype>Routing</subtype>
                <validation>R</validation>
                <position>6</position>
                <length>9</length>
            </field>
            <field id="5">Immediate Origin Routing Number
                <name>Immediate Origin Routing Number</name>
                <usage>M</usage>
                <type>N</type>
                <subtype>Routing</subtype>
                <validation>R</validation>
                <position>15</position>
                <length>9</length>
            </field>
            <field id="6">File Creation Date
                <name>File Creation Date</name>
                <usage>M</usage>
                <type>N</type>
                <subtype>Date</subtype>
                <validation>R</validation>
                <position>24</position>
                <length>8</length>
            </field>
            <field id="7">File Creation Time
                <name>File Creation Time</name>
                <usage>M</usage>
                <type>N</type>
                <subtype>Time</subtype>
                <validation>R</validation>
                <position>32</position>
                <length>4</length>
            </field>
            <field id="8">Resend Indicator
                <name>Resend Indicator</name>
                <usage>M</usage>
                <type>A</type>
                <dictonary comprehensive="true">
                    <value key="N">Original File</value>
                </dictonary>
                <validation>R</validation>
                <position>36</position>
                <length>1</length>
            </field>
            <field id="9">Immediate Destination Name
                <name>Immediate Destination Name</name>
                <usage>C</usage>
                <type>AN</type>
                <validation>P</validation>
                <position>37</position>
                <length>18</length>
            </field>
            <field id="10">Immediate Origin Name
                <name>Immediate Origin Name</name>
                <usage>C</usage>
                <type>AN</type>
                <validation>P</validation>
                <position>55</position>
                <length>18</length>
            </field>
            <field id="11">File ID Modifier
                <name>File ID Modifier</name>
                <usage>C</usage>
                <type>ANU</type>
                <validation>R</validation>
                <position>73</position>
                <length>1</length>
            </field>
            <field id="12">Country Code
                <name>Country Code</name>
                <usage>C</usage>
                <type>A</type>
                <subtype>Blank</subtype>
                <validation>N</validation>
                <position>74</position>
                <length>2</length>
            </field>
            <field id="13">User Field
                <name>User Field</name>
                <usage>O</usage>
                <type>ANS</type>
                <subtype>Blank</subtype>
                <validation>N</validation>
                <position>76</position>
                <length>4</length>
            </field>
            <field id="14">Companion Document Version Indicator
                <name>Companion Document Version Indicator</name>
                <usage>O</usage>
                <type>AN</type>
                <dictonary comprehensive="true">
                    <value key="1">UCD X9.100-187</value>
                </dictonary>
                <validation>P</validation>
                <position>80</position>
                <length>1</length>
            </field>
        </fields>
    </record>
    
    <record type="10">Cash Letter Header Record
        <name>Cash Letter Header Record</name>
        <type>10</type>
        <usage>M</usage>
        <validation>R</validation>
        <length>80</length>
        <fields count="16">
            <field id="1">
                <name>Record Type</name>
                <usage>M</usage>
                <position>1</position>
                <length>2</length>
                <type>N</type>
                <dictonary comprehensive="true" ref="recordType"/>
                <validation>R</validation>
            </field>
            <field id="2">
                <name>Collection Type Indicator</name>
                <usage>M</usage>
                <position>3</position>
                <length>2</length>
                <type>N</type>
                <dictonary comprehensive="false">
                    <value key='01'>Forward Presentment</value>
                    <value key='03'>Returns</value>
                </dictonary>
                <validation>R</validation>
            </field>
            <field id="3">
                <name>Destination Routing Number</name>
                <usage>M</usage>
                <position>5</position>
                <length>9</length>
                <type>N</type>
                <subtype>Routing</subtype>
                <validation>R</validation>
            </field>
            <field id="4">
                <name>ECE Institution Routing Number</name>
                <usage>M</usage>
                <position>14</position>
                <length>9</length>
                <type>N</type>
                <subtype>Routing</subtype>
                <validation>R</validation>
            </field>
            <field id="5">
                <name>Cash Letter Buisness Date</name>
                <usage>M</usage>
                <position>23</position>
                <length>8</length>
                <type>N</type>
                <subtype>Date</subtype>
                <validation>R</validation>
            </field>
            <field id="6">
                <name>Cash Letter Creation Date</name>
                <usage>M</usage>
                <position>31</position>
                <length>8</length>
                <type>N</type>
                <subtype>Date</subtype>
                <validation>R</validation>
            </field>
            <field id="7">
                <name>Cash Letter Creation Time</name>
                <usage>M</usage>
                <position>39</position>
                <length>4</length>
                <type>N</type>
                <subtype>Time</subtype>
                <validation>R</validation>
            </field>
            <field id="8">
                <name>Cash Letter Record Type Indicator</name>
                <usage>M</usage>
                <position>43</position>
                <length>1</length>
                <type>AN</type>
                <dictonary comprehensive="false"/>
                <validation>R</validation>
            </field>
            <field id="8">
                <name>Cash Letter Record Type Indicator</name>
                <usage>M</usage>
                <position>43</position>
                <length>1</length>
                <type>AN</type>
                <dictonary comprehensive="false"/>
                <validation>R</validation>
            </field>
            <field id="9">
                <name>Cash Letter Documentation Type Indicator</name>
                <usage>M</usage>
                <position>44</position>
                <length>1</length>
                <type>AN</type>
                <dictonary comprehensive="false">
                    <value key="C"/>
                </dictonary>
                <validation>R</validation>
            </field>
            <field id="10">
                <name>Cash Letter ID</name>
                <usage>M</usage>
                <position>45</position>
                <length>8</length>
                <type>AN</type>
                <validation>R</validation>
            </field>
